/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinosRouteImport } from './routes/treinos'
import { Route as TitulosRouteImport } from './routes/titulos'
import { Route as TierListRouteImport } from './routes/tier-list'
import { Route as TestesRouteImport } from './routes/testes'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PatchesRouteImport } from './routes/patches'
import { Route as OponentesRouteImport } from './routes/oponentes'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MuralRouteImport } from './routes/mural'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as JogadasRouteImport } from './routes/jogadas'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EquipesRouteImport } from './routes/equipes'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as DevRouteImport } from './routes/dev'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComposicoesRouteImport } from './routes/composicoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmistososRouteImport } from './routes/amistosos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as DevIndexRouteImport } from './routes/dev.index'
import { Route as BuildsIndexRouteImport } from './routes/builds.index'
import { Route as StaffUsersRouteImport } from './routes/staff.users'
import { Route as StaffTeamsRouteImport } from './routes/staff.teams'
import { Route as StaffStaffRouteImport } from './routes/staff.staff'
import { Route as StaffMarketingRouteImport } from './routes/staff.marketing'
import { Route as StaffDevRouteImport } from './routes/staff.dev'
import { Route as StaffAuditRouteImport } from './routes/staff.audit'
import { Route as JogadoresMemberIdRouteImport } from './routes/jogadores.$memberId'
import { Route as DevFeedbackRouteImport } from './routes/dev.feedback'
import { Route as BuildsPokemonRouteImport } from './routes/builds.$pokemon'
import { Route as StaffFinanceIndexRouteImport } from './routes/staff.finance.index'
import { Route as StaffFinanceWaitlistRouteImport } from './routes/staff.finance.waitlist'

const TreinosRoute = TreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const TitulosRoute = TitulosRouteImport.update({
  id: '/titulos',
  path: '/titulos',
  getParentRoute: () => rootRouteImport,
} as any)
const TierListRoute = TierListRouteImport.update({
  id: '/tier-list',
  path: '/tier-list',
  getParentRoute: () => rootRouteImport,
} as any)
const TestesRoute = TestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PatchesRoute = PatchesRouteImport.update({
  id: '/patches',
  path: '/patches',
  getParentRoute: () => rootRouteImport,
} as any)
const OponentesRoute = OponentesRouteImport.update({
  id: '/oponentes',
  path: '/oponentes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralRoute = MuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadasRoute = JogadasRouteImport.update({
  id: '/jogadas',
  path: '/jogadas',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipesRoute = EquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposicoesRoute = ComposicoesRouteImport.update({
  id: '/composicoes',
  path: '/composicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmistososRoute = AmistososRouteImport.update({
  id: '/amistosos',
  path: '/amistosos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRoute,
} as any)
const BuildsIndexRoute = BuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildsRoute,
} as any)
const StaffUsersRoute = StaffUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => StaffRoute,
} as any)
const StaffTeamsRoute = StaffTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => StaffRoute,
} as any)
const StaffStaffRoute = StaffStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMarketingRoute = StaffMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDevRoute = StaffDevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAuditRoute = StaffAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => StaffRoute,
} as any)
const JogadoresMemberIdRoute = JogadoresMemberIdRouteImport.update({
  id: '/jogadores/$memberId',
  path: '/jogadores/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFeedbackRoute = DevFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => DevRoute,
} as any)
const BuildsPokemonRoute = BuildsPokemonRouteImport.update({
  id: '/$pokemon',
  path: '/$pokemon',
  getParentRoute: () => BuildsRoute,
} as any)
const StaffFinanceIndexRoute = StaffFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFinanceWaitlistRoute = StaffFinanceWaitlistRouteImport.update({
  id: '/finance/waitlist',
  path: '/finance/waitlist',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/amistosos': typeof AmistososRoute
  '/auth': typeof AuthRoute
  '/builds': typeof BuildsRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/composicoes': typeof ComposicoesRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/dev': typeof DevRouteWithChildren
  '/draft': typeof DraftRoute
  '/equipes': typeof EquipesRoute
  '/feedback': typeof FeedbackRoute
  '/jogadas': typeof JogadasRoute
  '/landing': typeof LandingRoute
  '/mural': typeof MuralRoute
  '/onboarding': typeof OnboardingRoute
  '/oponentes': typeof OponentesRoute
  '/patches': typeof PatchesRoute
  '/perfil': typeof PerfilRoute
  '/planner': typeof PlannerRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roster': typeof RosterRoute
  '/staff': typeof StaffRouteWithChildren
  '/testes': typeof TestesRoute
  '/tier-list': typeof TierListRoute
  '/titulos': typeof TitulosRoute
  '/treinos': typeof TreinosRoute
  '/builds/$pokemon': typeof BuildsPokemonRoute
  '/dev/feedback': typeof DevFeedbackRoute
  '/jogadores/$memberId': typeof JogadoresMemberIdRoute
  '/staff/audit': typeof StaffAuditRoute
  '/staff/dev': typeof StaffDevRoute
  '/staff/marketing': typeof StaffMarketingRoute
  '/staff/staff': typeof StaffStaffRoute
  '/staff/teams': typeof StaffTeamsRoute
  '/staff/users': typeof StaffUsersRoute
  '/builds/': typeof BuildsIndexRoute
  '/dev/': typeof DevIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/finance/waitlist': typeof StaffFinanceWaitlistRoute
  '/staff/finance/': typeof StaffFinanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/amistosos': typeof AmistososRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/composicoes': typeof ComposicoesRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/draft': typeof DraftRoute
  '/equipes': typeof EquipesRoute
  '/feedback': typeof FeedbackRoute
  '/jogadas': typeof JogadasRoute
  '/landing': typeof LandingRoute
  '/mural': typeof MuralRoute
  '/onboarding': typeof OnboardingRoute
  '/oponentes': typeof OponentesRoute
  '/patches': typeof PatchesRoute
  '/perfil': typeof PerfilRoute
  '/planner': typeof PlannerRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roster': typeof RosterRoute
  '/testes': typeof TestesRoute
  '/tier-list': typeof TierListRoute
  '/titulos': typeof TitulosRoute
  '/treinos': typeof TreinosRoute
  '/builds/$pokemon': typeof BuildsPokemonRoute
  '/dev/feedback': typeof DevFeedbackRoute
  '/jogadores/$memberId': typeof JogadoresMemberIdRoute
  '/staff/audit': typeof StaffAuditRoute
  '/staff/dev': typeof StaffDevRoute
  '/staff/marketing': typeof StaffMarketingRoute
  '/staff/staff': typeof StaffStaffRoute
  '/staff/teams': typeof StaffTeamsRoute
  '/staff/users': typeof StaffUsersRoute
  '/builds': typeof BuildsIndexRoute
  '/dev': typeof DevIndexRoute
  '/staff': typeof StaffIndexRoute
  '/staff/finance/waitlist': typeof StaffFinanceWaitlistRoute
  '/staff/finance': typeof StaffFinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/amistosos': typeof AmistososRoute
  '/auth': typeof AuthRoute
  '/builds': typeof BuildsRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/composicoes': typeof ComposicoesRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/dev': typeof DevRouteWithChildren
  '/draft': typeof DraftRoute
  '/equipes': typeof EquipesRoute
  '/feedback': typeof FeedbackRoute
  '/jogadas': typeof JogadasRoute
  '/landing': typeof LandingRoute
  '/mural': typeof MuralRoute
  '/onboarding': typeof OnboardingRoute
  '/oponentes': typeof OponentesRoute
  '/patches': typeof PatchesRoute
  '/perfil': typeof PerfilRoute
  '/planner': typeof PlannerRoute
  '/planos': typeof PlanosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roster': typeof RosterRoute
  '/staff': typeof StaffRouteWithChildren
  '/testes': typeof TestesRoute
  '/tier-list': typeof TierListRoute
  '/titulos': typeof TitulosRoute
  '/treinos': typeof TreinosRoute
  '/builds/$pokemon': typeof BuildsPokemonRoute
  '/dev/feedback': typeof DevFeedbackRoute
  '/jogadores/$memberId': typeof JogadoresMemberIdRoute
  '/staff/audit': typeof StaffAuditRoute
  '/staff/dev': typeof StaffDevRoute
  '/staff/marketing': typeof StaffMarketingRoute
  '/staff/staff': typeof StaffStaffRoute
  '/staff/teams': typeof StaffTeamsRoute
  '/staff/users': typeof StaffUsersRoute
  '/builds/': typeof BuildsIndexRoute
  '/dev/': typeof DevIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/staff/finance/waitlist': typeof StaffFinanceWaitlistRoute
  '/staff/finance/': typeof StaffFinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/admin'
    | '/agenda'
    | '/amistosos'
    | '/auth'
    | '/builds'
    | '/cadastro'
    | '/composicoes'
    | '/dashboard'
    | '/design'
    | '/dev'
    | '/draft'
    | '/equipes'
    | '/feedback'
    | '/jogadas'
    | '/landing'
    | '/mural'
    | '/onboarding'
    | '/oponentes'
    | '/patches'
    | '/perfil'
    | '/planner'
    | '/planos'
    | '/reset-password'
    | '/roster'
    | '/staff'
    | '/testes'
    | '/tier-list'
    | '/titulos'
    | '/treinos'
    | '/builds/$pokemon'
    | '/dev/feedback'
    | '/jogadores/$memberId'
    | '/staff/audit'
    | '/staff/dev'
    | '/staff/marketing'
    | '/staff/staff'
    | '/staff/teams'
    | '/staff/users'
    | '/builds/'
    | '/dev/'
    | '/staff/'
    | '/staff/finance/waitlist'
    | '/staff/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceitar-convite'
    | '/admin'
    | '/agenda'
    | '/amistosos'
    | '/auth'
    | '/cadastro'
    | '/composicoes'
    | '/dashboard'
    | '/design'
    | '/draft'
    | '/equipes'
    | '/feedback'
    | '/jogadas'
    | '/landing'
    | '/mural'
    | '/onboarding'
    | '/oponentes'
    | '/patches'
    | '/perfil'
    | '/planner'
    | '/planos'
    | '/reset-password'
    | '/roster'
    | '/testes'
    | '/tier-list'
    | '/titulos'
    | '/treinos'
    | '/builds/$pokemon'
    | '/dev/feedback'
    | '/jogadores/$memberId'
    | '/staff/audit'
    | '/staff/dev'
    | '/staff/marketing'
    | '/staff/staff'
    | '/staff/teams'
    | '/staff/users'
    | '/builds'
    | '/dev'
    | '/staff'
    | '/staff/finance/waitlist'
    | '/staff/finance'
  id:
    | '__root__'
    | '/'
    | '/aceitar-convite'
    | '/admin'
    | '/agenda'
    | '/amistosos'
    | '/auth'
    | '/builds'
    | '/cadastro'
    | '/composicoes'
    | '/dashboard'
    | '/design'
    | '/dev'
    | '/draft'
    | '/equipes'
    | '/feedback'
    | '/jogadas'
    | '/landing'
    | '/mural'
    | '/onboarding'
    | '/oponentes'
    | '/patches'
    | '/perfil'
    | '/planner'
    | '/planos'
    | '/reset-password'
    | '/roster'
    | '/staff'
    | '/testes'
    | '/tier-list'
    | '/titulos'
    | '/treinos'
    | '/builds/$pokemon'
    | '/dev/feedback'
    | '/jogadores/$memberId'
    | '/staff/audit'
    | '/staff/dev'
    | '/staff/marketing'
    | '/staff/staff'
    | '/staff/teams'
    | '/staff/users'
    | '/builds/'
    | '/dev/'
    | '/staff/'
    | '/staff/finance/waitlist'
    | '/staff/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AceitarConviteRoute: typeof AceitarConviteRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AmistososRoute: typeof AmistososRoute
  AuthRoute: typeof AuthRoute
  BuildsRoute: typeof BuildsRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ComposicoesRoute: typeof ComposicoesRoute
  DashboardRoute: typeof DashboardRoute
  DesignRoute: typeof DesignRoute
  DevRoute: typeof DevRouteWithChildren
  DraftRoute: typeof DraftRoute
  EquipesRoute: typeof EquipesRoute
  FeedbackRoute: typeof FeedbackRoute
  JogadasRoute: typeof JogadasRoute
  LandingRoute: typeof LandingRoute
  MuralRoute: typeof MuralRoute
  OnboardingRoute: typeof OnboardingRoute
  OponentesRoute: typeof OponentesRoute
  PatchesRoute: typeof PatchesRoute
  PerfilRoute: typeof PerfilRoute
  PlannerRoute: typeof PlannerRoute
  PlanosRoute: typeof PlanosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RosterRoute: typeof RosterRoute
  StaffRoute: typeof StaffRouteWithChildren
  TestesRoute: typeof TestesRoute
  TierListRoute: typeof TierListRoute
  TitulosRoute: typeof TitulosRoute
  TreinosRoute: typeof TreinosRoute
  JogadoresMemberIdRoute: typeof JogadoresMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinos': {
      id: '/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof TreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titulos': {
      id: '/titulos'
      path: '/titulos'
      fullPath: '/titulos'
      preLoaderRoute: typeof TitulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tier-list': {
      id: '/tier-list'
      path: '/tier-list'
      fullPath: '/tier-list'
      preLoaderRoute: typeof TierListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testes': {
      id: '/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof TestesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patches': {
      id: '/patches'
      path: '/patches'
      fullPath: '/patches'
      preLoaderRoute: typeof PatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oponentes': {
      id: '/oponentes'
      path: '/oponentes'
      fullPath: '/oponentes'
      preLoaderRoute: typeof OponentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mural': {
      id: '/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof MuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadas': {
      id: '/jogadas'
      path: '/jogadas'
      fullPath: '/jogadas'
      preLoaderRoute: typeof JogadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipes': {
      id: '/equipes'
      path: '/equipes'
      fullPath: '/equipes'
      preLoaderRoute: typeof EquipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composicoes': {
      id: '/composicoes'
      path: '/composicoes'
      fullPath: '/composicoes'
      preLoaderRoute: typeof ComposicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amistosos': {
      id: '/amistosos'
      path: '/amistosos'
      fullPath: '/amistosos'
      preLoaderRoute: typeof AmistososRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRoute
    }
    '/builds/': {
      id: '/builds/'
      path: '/'
      fullPath: '/builds/'
      preLoaderRoute: typeof BuildsIndexRouteImport
      parentRoute: typeof BuildsRoute
    }
    '/staff/users': {
      id: '/staff/users'
      path: '/users'
      fullPath: '/staff/users'
      preLoaderRoute: typeof StaffUsersRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/teams': {
      id: '/staff/teams'
      path: '/teams'
      fullPath: '/staff/teams'
      preLoaderRoute: typeof StaffTeamsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/staff': {
      id: '/staff/staff'
      path: '/staff'
      fullPath: '/staff/staff'
      preLoaderRoute: typeof StaffStaffRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/marketing': {
      id: '/staff/marketing'
      path: '/marketing'
      fullPath: '/staff/marketing'
      preLoaderRoute: typeof StaffMarketingRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/dev': {
      id: '/staff/dev'
      path: '/dev'
      fullPath: '/staff/dev'
      preLoaderRoute: typeof StaffDevRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/audit': {
      id: '/staff/audit'
      path: '/audit'
      fullPath: '/staff/audit'
      preLoaderRoute: typeof StaffAuditRouteImport
      parentRoute: typeof StaffRoute
    }
    '/jogadores/$memberId': {
      id: '/jogadores/$memberId'
      path: '/jogadores/$memberId'
      fullPath: '/jogadores/$memberId'
      preLoaderRoute: typeof JogadoresMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/feedback': {
      id: '/dev/feedback'
      path: '/feedback'
      fullPath: '/dev/feedback'
      preLoaderRoute: typeof DevFeedbackRouteImport
      parentRoute: typeof DevRoute
    }
    '/builds/$pokemon': {
      id: '/builds/$pokemon'
      path: '/$pokemon'
      fullPath: '/builds/$pokemon'
      preLoaderRoute: typeof BuildsPokemonRouteImport
      parentRoute: typeof BuildsRoute
    }
    '/staff/finance/': {
      id: '/staff/finance/'
      path: '/finance'
      fullPath: '/staff/finance/'
      preLoaderRoute: typeof StaffFinanceIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/finance/waitlist': {
      id: '/staff/finance/waitlist'
      path: '/finance/waitlist'
      fullPath: '/staff/finance/waitlist'
      preLoaderRoute: typeof StaffFinanceWaitlistRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface BuildsRouteChildren {
  BuildsPokemonRoute: typeof BuildsPokemonRoute
  BuildsIndexRoute: typeof BuildsIndexRoute
}

const BuildsRouteChildren: BuildsRouteChildren = {
  BuildsPokemonRoute: BuildsPokemonRoute,
  BuildsIndexRoute: BuildsIndexRoute,
}

const BuildsRouteWithChildren =
  BuildsRoute._addFileChildren(BuildsRouteChildren)

interface DevRouteChildren {
  DevFeedbackRoute: typeof DevFeedbackRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevFeedbackRoute: DevFeedbackRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

interface StaffRouteChildren {
  StaffAuditRoute: typeof StaffAuditRoute
  StaffDevRoute: typeof StaffDevRoute
  StaffMarketingRoute: typeof StaffMarketingRoute
  StaffStaffRoute: typeof StaffStaffRoute
  StaffTeamsRoute: typeof StaffTeamsRoute
  StaffUsersRoute: typeof StaffUsersRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffFinanceWaitlistRoute: typeof StaffFinanceWaitlistRoute
  StaffFinanceIndexRoute: typeof StaffFinanceIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAuditRoute: StaffAuditRoute,
  StaffDevRoute: StaffDevRoute,
  StaffMarketingRoute: StaffMarketingRoute,
  StaffStaffRoute: StaffStaffRoute,
  StaffTeamsRoute: StaffTeamsRoute,
  StaffUsersRoute: StaffUsersRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffFinanceWaitlistRoute: StaffFinanceWaitlistRoute,
  StaffFinanceIndexRoute: StaffFinanceIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AceitarConviteRoute: AceitarConviteRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AmistososRoute: AmistososRoute,
  AuthRoute: AuthRoute,
  BuildsRoute: BuildsRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ComposicoesRoute: ComposicoesRoute,
  DashboardRoute: DashboardRoute,
  DesignRoute: DesignRoute,
  DevRoute: DevRouteWithChildren,
  DraftRoute: DraftRoute,
  EquipesRoute: EquipesRoute,
  FeedbackRoute: FeedbackRoute,
  JogadasRoute: JogadasRoute,
  LandingRoute: LandingRoute,
  MuralRoute: MuralRoute,
  OnboardingRoute: OnboardingRoute,
  OponentesRoute: OponentesRoute,
  PatchesRoute: PatchesRoute,
  PerfilRoute: PerfilRoute,
  PlannerRoute: PlannerRoute,
  PlanosRoute: PlanosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RosterRoute: RosterRoute,
  StaffRoute: StaffRouteWithChildren,
  TestesRoute: TestesRoute,
  TierListRoute: TierListRoute,
  TitulosRoute: TitulosRoute,
  TreinosRoute: TreinosRoute,
  JogadoresMemberIdRoute: JogadoresMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
