/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinosRouteImport } from './routes/treinos'
import { Route as TierListRouteImport } from './routes/tier-list'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as OponentesRouteImport } from './routes/oponentes'
import { Route as MuralRouteImport } from './routes/mural'
import { Route as JogadasRouteImport } from './routes/jogadas'
import { Route as DraftRouteImport } from './routes/draft'
import { Route as ComposicoesRouteImport } from './routes/composicoes'
import { Route as BuildsRouteImport } from './routes/builds'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AmistososRouteImport } from './routes/amistosos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogadoresMemberIdRouteImport } from './routes/jogadores.$memberId'

const TreinosRoute = TreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const TierListRoute = TierListRouteImport.update({
  id: '/tier-list',
  path: '/tier-list',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const OponentesRoute = OponentesRouteImport.update({
  id: '/oponentes',
  path: '/oponentes',
  getParentRoute: () => rootRouteImport,
} as any)
const MuralRoute = MuralRouteImport.update({
  id: '/mural',
  path: '/mural',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadasRoute = JogadasRouteImport.update({
  id: '/jogadas',
  path: '/jogadas',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoute = DraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposicoesRoute = ComposicoesRouteImport.update({
  id: '/composicoes',
  path: '/composicoes',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildsRoute = BuildsRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AmistososRoute = AmistososRouteImport.update({
  id: '/amistosos',
  path: '/amistosos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresMemberIdRoute = JogadoresMemberIdRouteImport.update({
  id: '/jogadores/$memberId',
  path: '/jogadores/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/amistosos': typeof AmistososRoute
  '/auth': typeof AuthRoute
  '/builds': typeof BuildsRoute
  '/composicoes': typeof ComposicoesRoute
  '/draft': typeof DraftRoute
  '/jogadas': typeof JogadasRoute
  '/mural': typeof MuralRoute
  '/oponentes': typeof OponentesRoute
  '/planner': typeof PlannerRoute
  '/roster': typeof RosterRoute
  '/tier-list': typeof TierListRoute
  '/treinos': typeof TreinosRoute
  '/jogadores/$memberId': typeof JogadoresMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/amistosos': typeof AmistososRoute
  '/auth': typeof AuthRoute
  '/builds': typeof BuildsRoute
  '/composicoes': typeof ComposicoesRoute
  '/draft': typeof DraftRoute
  '/jogadas': typeof JogadasRoute
  '/mural': typeof MuralRoute
  '/oponentes': typeof OponentesRoute
  '/planner': typeof PlannerRoute
  '/roster': typeof RosterRoute
  '/tier-list': typeof TierListRoute
  '/treinos': typeof TreinosRoute
  '/jogadores/$memberId': typeof JogadoresMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agenda': typeof AgendaRoute
  '/amistosos': typeof AmistososRoute
  '/auth': typeof AuthRoute
  '/builds': typeof BuildsRoute
  '/composicoes': typeof ComposicoesRoute
  '/draft': typeof DraftRoute
  '/jogadas': typeof JogadasRoute
  '/mural': typeof MuralRoute
  '/oponentes': typeof OponentesRoute
  '/planner': typeof PlannerRoute
  '/roster': typeof RosterRoute
  '/tier-list': typeof TierListRoute
  '/treinos': typeof TreinosRoute
  '/jogadores/$memberId': typeof JogadoresMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/amistosos'
    | '/auth'
    | '/builds'
    | '/composicoes'
    | '/draft'
    | '/jogadas'
    | '/mural'
    | '/oponentes'
    | '/planner'
    | '/roster'
    | '/tier-list'
    | '/treinos'
    | '/jogadores/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agenda'
    | '/amistosos'
    | '/auth'
    | '/builds'
    | '/composicoes'
    | '/draft'
    | '/jogadas'
    | '/mural'
    | '/oponentes'
    | '/planner'
    | '/roster'
    | '/tier-list'
    | '/treinos'
    | '/jogadores/$memberId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/amistosos'
    | '/auth'
    | '/builds'
    | '/composicoes'
    | '/draft'
    | '/jogadas'
    | '/mural'
    | '/oponentes'
    | '/planner'
    | '/roster'
    | '/tier-list'
    | '/treinos'
    | '/jogadores/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgendaRoute: typeof AgendaRoute
  AmistososRoute: typeof AmistososRoute
  AuthRoute: typeof AuthRoute
  BuildsRoute: typeof BuildsRoute
  ComposicoesRoute: typeof ComposicoesRoute
  DraftRoute: typeof DraftRoute
  JogadasRoute: typeof JogadasRoute
  MuralRoute: typeof MuralRoute
  OponentesRoute: typeof OponentesRoute
  PlannerRoute: typeof PlannerRoute
  RosterRoute: typeof RosterRoute
  TierListRoute: typeof TierListRoute
  TreinosRoute: typeof TreinosRoute
  JogadoresMemberIdRoute: typeof JogadoresMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinos': {
      id: '/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof TreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tier-list': {
      id: '/tier-list'
      path: '/tier-list'
      fullPath: '/tier-list'
      preLoaderRoute: typeof TierListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oponentes': {
      id: '/oponentes'
      path: '/oponentes'
      fullPath: '/oponentes'
      preLoaderRoute: typeof OponentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mural': {
      id: '/mural'
      path: '/mural'
      fullPath: '/mural'
      preLoaderRoute: typeof MuralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadas': {
      id: '/jogadas'
      path: '/jogadas'
      fullPath: '/jogadas'
      preLoaderRoute: typeof JogadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft': {
      id: '/draft'
      path: '/draft'
      fullPath: '/draft'
      preLoaderRoute: typeof DraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composicoes': {
      id: '/composicoes'
      path: '/composicoes'
      fullPath: '/composicoes'
      preLoaderRoute: typeof ComposicoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builds': {
      id: '/builds'
      path: '/builds'
      fullPath: '/builds'
      preLoaderRoute: typeof BuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amistosos': {
      id: '/amistosos'
      path: '/amistosos'
      fullPath: '/amistosos'
      preLoaderRoute: typeof AmistososRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores/$memberId': {
      id: '/jogadores/$memberId'
      path: '/jogadores/$memberId'
      fullPath: '/jogadores/$memberId'
      preLoaderRoute: typeof JogadoresMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgendaRoute: AgendaRoute,
  AmistososRoute: AmistososRoute,
  AuthRoute: AuthRoute,
  BuildsRoute: BuildsRoute,
  ComposicoesRoute: ComposicoesRoute,
  DraftRoute: DraftRoute,
  JogadasRoute: JogadasRoute,
  MuralRoute: MuralRoute,
  OponentesRoute: OponentesRoute,
  PlannerRoute: PlannerRoute,
  RosterRoute: RosterRoute,
  TierListRoute: TierListRoute,
  TreinosRoute: TreinosRoute,
  JogadoresMemberIdRoute: JogadoresMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
